In [ ]:
# request 모듈로 웹사이트 내용을 가져오기
# bs4fh html 파싱하기
# pands로 데이터 구조화시키기
# matplotip 으로 그래프 출력 => 시각화 모듈

In [4]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [11]:
source= requests.get('https://www.weather.go.kr/weather/observation/currentweather.jsp')
soup=BeautifulSoup(source.content, "html.parser")

In [12]:
table=soup.find('table',{'class':'table_develop3'})
data=[]

In [33]:
print('""'*30)
print('\n 오늘의 온도 습도 \n')
print('""'*30)

for tr in table.find_all('tr'):
    tds=list(tr.find_all('td'))
    for td in tds:
        if td.find('a'):
            location =td.find('a').text #지역
            temp= tds[5].text #온도
            humidity=tds[9].text
            print("{0:<7} {1:<7} {2:7}".format(location,temp,humidity)) #{0:<7} {1:<7} {2:7} 정렬의 의미 출력보기좋게
            data.append([location,temp,humidity])
            
print('""'*30)
print('\n 오늘의 온도 습도 \n')
print('""'*30)

print(data)
with open('weather.csv','w') as f:
    f.write('지역,온도,습도 \n')
    for i in data:
        f.write('{0},{1},{2}\n'.format(i[0],i[1],i[2]))

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

 오늘의 온도 습도

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
강릉      16.7    58
강진군     13.4    83
강화      13.2    62
거제      15.7    66
거창      9.2     83
경주시     13.9    66
고산      18.6    70
고창      10.7    97
고창군     12.1    90
고흥      14.9    81
광양시     15.4    65
광주      12.7    91
구미      11.8    78
군산      13.0    89
금산      8.3     95
김해시     13.1    68
남원      9.7     87
남해      15.1    65
대관령     9.8     84
대구      12.7    76
대전      10.9    97
동두천     11.7    89
동해      17.3    52
목포      14.5    85
문경      9.9     93
밀양      11.1    79
백령도     15.4    33
보령      15.3    78
보성군     15.4    74
보은      7.9     100
봉화      7.6     94
부산      17.0    50
부안      13.6    87
부여      9.6     100
북강릉     15.8    55
북창원     14.7    71
북춘천     9.7     99
산청      10.2    85
상주      11.3    86
서귀포     19.0    61
서산      14.4    89
서울      12.4    87
성산      17.6    68
세종      10.8    93
속초      16.8    43
수원      13.5    92
순창군     8.5     99
순천      14.2    82
안동      8.9     94
양산시     15.4    69
양평      10.1    95
여수      15.7    61
영광군     12.3    91
영덕      16.1    59
영월      7.8     98
영주      10.5    86
영천      12.2    77
완도      17.4    72
울릉도     16.9    62
울산      15.5    62
울진      16.7    58
원주      10.6    81
의령군     11.1    88
의성      8.6     92
이천      8.3     100
인제      9.1     99
인천      12.9    62
임실      8.8     93
장수      8.3     89
장흥      11.6    91
전주      13.3    81
정선군     9.8     84
정읍      12.5    89
제주      18.5    71
제천      9.4     91
진도군     14.1    91
진주      12.2    87
창원      14.8    60
천안      9.7     100
철원      7.5     100
청송군     8.5     81
청주      12.3    82
추풍령     11.3    78
춘천      10.1    97
충주      10.5    90
태백      11.7    64
통영      16.3    65
파주      9.3     100
포항      15.6    64
함양군     9.1     82
합천      10.4    91
해남      11.7    91
홍성      13.4    93
홍천      9.4     88
흑산도     17.6    73
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

 오늘의 온도 습도

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

In [29]:

df = pd.read_csv('weather.csv', index_col='지역' ,encoding='euc-kr')
city_df=df.loc[['서울','인천','대전','대구','광주','부산']]
df

       온도  습도
지역
강릉   16.7   58
강진군  13.4   83
강화   13.2   62
거제   15.7   66
거창    9.2   83
..    ...  ...
합천   10.4   91
해남   11.7   91
홍성   13.4   93
홍천    9.4   88
흑산도  17.6   73

[665 rows x 2 columns]

In [30]:
city_df

      온도  습도
지역
서울  12.4   87
서울  12.4   87
서울  12.4   87
서울  12.4   87
서울  12.4   87
서울  12.4   87
서울  12.4   87
인천  12.9   62
인천  12.9   62
인천  12.9   62
인천  12.9   62
인천  12.9   62
인천  12.9   62
인천  12.9   62
대전  10.9   97
대전  10.9   97
대전  10.9   97
대전  10.9   97
대전  10.9   97
대전  10.9   97
대전  10.9   97
대구  12.7   76
대구  12.7   76
대구  12.7   76
대구  12.7   76
대구  12.7   76
대구  12.7   76
대구  12.7   76
광주  12.7   91
광주  12.7   91
광주  12.7   91
광주  12.7   91
광주  12.7   91
광주  12.7   91
광주  12.7   91
부산  17.0   50
부산  17.0   50
부산  17.0   50
부산  17.0   50
부산  17.0   50
부산  17.0   50
부산  17.0   50

In [31]:

df1 = pd.read_csv('weather.csv' ,encoding='euc-kr')
# city_df=df.loc[['서울','인천','대전','대구','광주','부산']]
df1

      지역    온도  습도
0     강릉  16.7   58
1    강진군  13.4   83
2     강화  13.2   62
3     거제  15.7   66
4     거창   9.2   83
..   ...   ...  ...
660   합천  10.4   91
661   해남  11.7   91
662   홍성  13.4   93
663   홍천   9.4   88
664  흑산도  17.6   73

[665 rows x 3 columns]